export type Service = 'lente' | 'reloj' | 'senal';
export type DistributionFault = 'missing-service' | 'underpower' | 'overpower' | 'source-overload' | 'ampacity' | 'fuse-undersized' | 'fuse-oversized' | 'not-isolatable' | 'ok';
export interface DistributionBranch { service: Service; enabled: boolean; resistance: number; ampacity: number; fuseRating: number; isolatable: boolean; }
export interface BranchDiagnostic { service: Service; current: number; voltage: number; power: number; fault: DistributionFault | 'ok'; }
export interface LighthouseDistributionDcInput { voltage: number; sourceLimit: number; branches: readonly DistributionBranch[]; }
export interface LighthouseDistributionDcResult { valid: boolean; fault: DistributionFault; totalCurrent: number; diagnostics: readonly BranchDiagnostic[]; signature: string; feedback: string; }
const bands: Record<Service, readonly [number, number]> = { lente: [8, 30], reloj: [5, 30], senal: [3, 30] };
export function evaluateLighthouseDistributionDc(input: LighthouseDistributionDcInput): LighthouseDistributionDcResult {
 const active = input.branches.filter(b=>b.enabled); const services=new Set(active.map(b=>b.service));
 const diagnostics= input.branches.map(b=>{ const current=b.enabled&&b.resistance>0?input.voltage/b.resistance:0; const power=input.voltage*current; const [min,max]=bands[b.service]; let fault:DistributionFault|'ok'=!b.enabled?'missing-service':power<min?'underpower':power>max?'overpower':current>b.ampacity?'ampacity':b.fuseRating<current?'fuse-undersized':b.fuseRating>b.ampacity?'fuse-oversized':!b.isolatable?'not-isolatable':'ok'; return {service:b.service,current,voltage:b.enabled?input.voltage:0,power,fault}; });
 const totalCurrent=diagnostics.reduce((s,b)=>s+b.current,0); const required:Service[]=['lente','reloj','senal']; const fault:DistributionFault=!required.every(s=>services.has(s))?'missing-service':totalCurrent>input.sourceLimit?'source-overload':(diagnostics.find(d=>d.fault!=='ok')?.fault??'ok') as DistributionFault;
 const signature=input.branches.map(b=>`${b.service}:${+b.enabled}:${b.resistance}:${b.ampacity}:${b.fuseRating}:${+b.isolatable}`).join('|'); const feedback:Record<DistributionFault,string>={ok:'Los tres servicios están operativos y se pueden mantener.','missing-service':'Falta conectar lente, reloj o señal costera.','underpower':'Un servicio recibe poca entrega para operar.','overpower':'Un servicio recibe demasiada entrega.','source-overload':'El Tronco supera su límite de Río.','ampacity':'Un Camino se calienta porque su calibre es insuficiente.','fuse-undersized':'El fusible se abre antes de que el ramal pueda operar.','fuse-oversized':'El fusible no protege el calibre del Camino.','not-isolatable':'Falta un interruptor para aislar un ramal durante el mantenimiento.'}; return {valid:fault==='ok',fault,totalCurrent,diagnostics,signature,feedback:feedback[fault]};
}
export interface TransferProgress { firstSignature?:string; complete:boolean; }
export function recordCommission(p:TransferProgress,r:LighthouseDistributionDcResult):TransferProgress { if(!r.valid)return p; return !p.firstSignature?{firstSignature:r.signature,complete:false}:{firstSignature:p.firstSignature,complete:p.firstSignature!==r.signature}; }
