import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const out=new URL('../output/playwright/',import.meta.url);await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const report={startedAt:new Date().toISOString(),checks:[],errors:[]};
try{
  const context=await browser.newContext({viewport:{width:1280,height:720}});
  const page=await context.newPage();page.setDefaultTimeout(5000);page.on('pageerror',e=>report.errors.push(e.message));
  await page.routeWebSocket('**',ws=>ws.close());
  await page.goto('http://127.0.0.1:4173');
  await page.getByRole('button',{name:'Opciones',exact:true}).focus();
  await page.keyboard.press('Enter');
  await page.getByRole('heading',{name:'Preparar el viaje',exact:true}).waitFor();
  await page.getByRole('dialog',{name:'Preparar el viaje',exact:true}).waitFor();
  await page.keyboard.press('Shift+Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'import-open');
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Cerrar');
  report.checks.push('Title buttons activate with Enter; options trap focus in both directions');
  await page.getByLabel('Silenciar',{exact:true}).check();
  await page.getByLabel('Lectura instantánea',{exact:true}).check();
  await page.getByLabel('Detalle visual',{exact:true}).selectOption('low');
  await page.getByRole('button',{name:'Volver',exact:true}).focus();
  await page.keyboard.press('Enter');
  await page.reload();
  await page.getByRole('button',{name:'Opciones',exact:true}).click();
  assert.equal(await page.getByLabel('Silenciar',{exact:true}).isChecked(),true);
  assert.equal(await page.getByLabel('Detalle visual',{exact:true}).inputValue(),'low');
  await page.screenshot({animations:'disabled',path:new URL('ui-options-1280.png',out).pathname.slice(1)});
  report.checks.push('Settings/mute/text/quality persisted across actual reload');
  await page.getByLabel('Detalle visual',{exact:true}).focus();
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Cruzar el Portal'}).click();
  await page.waitForFunction(()=>window.__ohmdal?.mode==='dialogue',null,{timeout:15000});
  const line=await page.locator('#dialogue-text').innerText();
  assert.ok(line.length>30);
  await page.keyboard.press('Enter');await page.waitForTimeout(100);
  const second=await page.locator('#dialogue-text').innerText();
  assert.ok((await page.locator('#dialogue-announcement').innerText()).includes(second));
  await page.reload();await page.getByRole('button',{name:'Continuar el viaje',exact:true}).click();
  await page.waitForFunction(()=>window.__ohmdal?.mode==='dialogue');await page.waitForTimeout(100);
  assert.equal(await page.locator('#dialogue-text').innerText(),second);
  report.checks.push('Mid-conversation reload resumes the exact dialogue line');
  for(let i=0;i<6;i++){if(await page.evaluate(()=>__ohmdal.mode)==='dialogue'){await page.keyboard.press('Enter');await page.waitForTimeout(100);}}
  await page.waitForFunction(()=>__ohmdal.mode==='world');
  const start=await page.evaluate(()=>__ohmdal.world.getPlayerPosition());
  await page.keyboard.down('d');await page.waitForTimeout(450);await page.keyboard.up('d');
  const moved=await page.evaluate(()=>__ohmdal.world.getPlayerPosition());assert.ok(Math.hypot(moved[0]-start[0],moved[1]-start[1])>.4);
  await page.keyboard.press('Escape');
  const paused=await page.evaluate(()=>__ohmdal.world.getPlayerPosition());await page.keyboard.down('w');await page.waitForTimeout(350);await page.keyboard.up('w');
  assert.deepEqual(await page.evaluate(()=>__ohmdal.world.getPlayerPosition()),paused);
  await page.keyboard.press('Escape');
  report.checks.push('Keyboard movement works; pause prevents drift');
  await page.keyboard.press('j');await page.getByRole('heading',{name:'La Bitácora',exact:true}).waitFor();await page.screenshot({animations:'disabled',path:new URL('ui-journal-1280.png',out).pathname.slice(1)});await page.keyboard.press('Escape');
  await page.keyboard.press('m');await page.getByRole('heading',{name:'Caminos de Ohmdal',exact:true}).waitFor();await page.screenshot({animations:'disabled',path:new URL('ui-map-1280.png',out).pathname.slice(1)});await page.keyboard.press('Escape');
  report.checks.push('Journal/map keyboard controls and close-cycle');
  await page.screenshot({animations:'disabled',path:new URL('ui-world-1280.png',out).pathname.slice(1)});
  const metrics=await page.evaluate(()=>({width:innerWidth,height:innerHeight,scrollW:document.documentElement.scrollWidth,scrollH:document.documentElement.scrollHeight}));assert.equal(metrics.width,metrics.scrollW);assert.equal(metrics.height,metrics.scrollH);
  report.checks.push('1280×720 fixed shell fits viewport');
  await page.keyboard.press('Escape');
  const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar bitácora',exact:true}).click();
  const download=await downloadEvent,saveFile=new URL('ui-exported-save.json',out).pathname.slice(1);await download.saveAs(saveFile);
  await page.getByRole('button',{name:'Guardar y volver al inicio',exact:true}).click();
  await page.getByRole('button',{name:'Opciones',exact:true}).click();
  await page.locator('#import-save').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{broken')});
  await page.locator('#toast').waitFor({state:'visible'});assert.equal(await page.locator('#modal-layer').isVisible(),true);
  await page.locator('#import-save').setInputFiles(saveFile);await page.waitForFunction(()=>__ohmdal.mode==='world');
  assert.equal(await page.evaluate(()=>__ohmdal.state.area),'portal');
  report.checks.push('Actual export/import restores the journey; malformed import leaves controls usable');
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const mp=await mobile.newPage();mp.setDefaultTimeout(5000);await mp.routeWebSocket('**',ws=>ws.close());
  mp.on('pageerror',e=>report.errors.push(e.message));await mp.goto('http://127.0.0.1:4173');await mp.screenshot({animations:'disabled',path:new URL('ui-title-390.png',out).pathname.slice(1)});
  await mp.getByRole('button',{name:'Opciones',exact:true}).click();await mp.screenshot({animations:'disabled',path:new URL('ui-options-390.png',out).pathname.slice(1)});
  assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth),390);assert.ok(await mp.getByLabel('Volumen',{exact:true}).isVisible());
  report.checks.push('390×844 title/options fit and controls remain reachable');
  await mobile.close();await context.close();assert.deepEqual(report.errors,[]);report.passed=true;
}catch(error){report.error=error.stack;report.passed=false;process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();await writeFile(new URL('ui-report.json',out),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2));}
