import { defineEducationCard, type EducationCard } from './types.ts';

const SOURCES =
  'Primarias: Escuela Técnica Otto Krause, Primer Ciclo (https://www.ottokrause.edu.ar/primer-ciclo/) y Electrónica (https://www.ottokrause.edu.ar/electronica/); CFE 15/07 Anexo III–Electrónica (https://www.inet.edu.ar/wp-content/uploads/2013/04/15-07-anexo03.pdf), medición, instrumental, fallas, documentación y seguridad. Internas: Biblia educativa §Ficha/§Escala V1–V2, vertical slice Beats 3–7 y backlog H1.1–H1.7. Reglas candidatas propias —no institucionales—: 5 V, 100/150 ohm, umbral 300 ohm, rangos, resoluciones, órdenes de diagnóstico, cuatro bloques de Bitácora y telemetría.';
const STATUS =
  'V1-ready-for-independent-audit; implementada y auto-revisada, pendiente de reproducción por un segundo agente; no V2 y no CANON-EDU.';
const TELEMETRY =
  'Sólo local y opt-in: códigos de estado, orden de acciones, configuración y completitud; nunca identidad, texto libre ni identificadores escolares.';

export const safetyCard = defineEducationCard({
  identifierVersion: 'H1.1-seguridad-virtual-v1',
  technicalName: 'Seguridad operativa en circuito DC ficticio, aislado y simulado de 5,00 V.',
  competencyLevel: 'F0 — Cultura de taller; compatible con seguridad, medición y documentación, sin equivalencia escolar.',
  sources: SOURCES,
  reviewerDate: 'Autoría DIR-EDU-001, 2026-08-02; auditor independiente pendiente.',
  prerequisites: 'Distinguir simulación de equipo real; reconocer fuente, retorno, nodo, referencia, V y estado energizado/desenergizado.',
  observableObjective: 'Inspeccionar, formular hipótesis, configurar y medir el modelo protegido, desenergizar antes de intervenir y documentar evidencia.',
  technicalModel: 'Fuente ideal virtual 5,00 V DC; las conexiones sólo cambian en deenergized_isolated y la medición energizada bloquea la topología.',
  variablesUnits: 'Vs y Vmed en V; rango en V; nodos V_PLUS/N1/N2/REF; power ∈ {deenergized_isolated, energized_locked}.',
  assumptionsLimits: 'Modelo determinista sin práctica física, AC, red, baterías de alta energía, tolerancias, transitorios ni seguridad certificada.',
  safetyRisks: 'La secuencia ficticia podría confundirse con receta real; la UI debe rotular simulación y bloquear intervención energizada o medición pasiva energizada.',
  initialPhenomenon: 'El indicador de Lumen está apagado y existen conexiones visibles, pero ninguna pieza aparece marcada de antemano como culpable.',
  researchQuestion: '¿Qué evidencia debe reunirse antes de intervenir el modelo y qué estados hacen inválida una acción?',
  expectedHypotheses: 'Puede existir un retorno abierto; una referencia o rango incorrectos impiden interpretar; sustituir sin evidencia no diagnostica.',
  availableInstruments: 'Esquema virtual, estado de alimentación, inspección, hipótesis estructurada, medidor virtual y Bitácora.',
  allowedInteractions: 'Configurar desenergizado; inspeccionar; registrar hipótesis; energizar bloqueado; medir V; desenergizar; medir pasivamente; intervenir y documentar.',
  simulatedConsequences: 'Una intervención energizada o con medición activa devuelve INTERVENTION_BLOCKED y conserva topología; un modo pasivo energizado es incompatible.',
  productiveErrors: 'Medir sin inspección; omitir referencia; confundir fuera de rango con cero; invertir puntas; intervenir durante medición; transferir a equipos reales.',
  evidenceHints: 'Nombrar la precondición faltante, mostrar A−B, energía y rango; no revelar la falla ni convertir una luz en prueba de seguridad.',
  masteryCriteria: 'Completa una secuencia válida, explica cada bloqueo y deja evidencia con magnitud, puntos, rango, valor, unidad y estado.',
  transfer: 'Aplica los mismos invariantes en la Puerta con otra disposición, sin introducir fuentes, herramientas ni prácticas físicas.',
  diegeticMetaphor: 'El taller detiene la ruta luminosa antes de tocar sus uniones y exige dejar una marca de lo observado.',
  metaphorLimit: 'La luz no es electricidad real, no prueba seguridad y el bloqueo del simulador no acredita una intervención física.',
  localFormalVocabulary: 'Ruta/marca/registro ↔ trayectoria/nodo/referencia/rango/desenergizado/evidencia.',
  initialLogEntry: 'Antes de mover una unión voy a dejar el modelo sin energía, inspeccionar y anotar qué comparación pondrá a prueba mi hipótesis.',
  revisedLogEntry: 'Medí V_PLUS respecto de REF en rango ±5,00 V: +5,00 V; no cambié conexiones energizadas y volví a aislar antes de intervenir.',
  accessibility: 'Estados, bloqueos, signo y unidades tienen texto; no dependen de color/sonido; teclado y táctil conservan foco y orden.',
  allowedTelemetry: TELEMETRY,
  deterministicTest: 'Probar inspección obligatoria, mismo nodo con precondiciones completas, límites inclusivos, polaridad, bloqueo con hash estable y no transferencia.',
  validationStatus: STATUS,
});

export const circuitCard = defineEducationCard({
  identifierVersion: 'H1.2-circuito-continuidad-v1',
  technicalName: 'Circuito DC serie completo, retorno abierto y continuidad virtual desenergizada.',
  competencyLevel: 'F0 — Circuito simple, medición y documentación; compatible con trayectos iniciales, sin acreditación.',
  sources: SOURCES,
  reviewerDate: 'Autoría DIR-EDU-001, 2026-08-02; cálculos auto-reproducidos; auditor independiente pendiente.',
  prerequisites: 'Reconocer fuente, resistores, nodo, retorno y referencia; leer V, mA, ohm y W.',
  observableObjective: 'Predecir y verificar una trayectoria completa, distinguir continuidad desenergizada de funcionamiento bajo carga y localizar el retorno abierto.',
  technicalModel: 'V_PLUS→R1 100 ohm→N1→R2 150 ohm→N2→retorno→REF; Vs=5,00 V; retorno closed u open.',
  variablesUnits: 'Vs/Vn/caídas en V; I en A o mA; R/Req en ohm; P en W; retorno closed/open.',
  assumptionsLimits: 'Componentes ideales; retorno closed=0 ohm; open=∞; fuente aislada en pruebas pasivas; sin tolerancia, fuga, ruido o límite activo.',
  safetyRisks: 'Continuidad y resistencia sólo existen desenergizadas/aisladas; ninguna lectura autoriza trabajo físico ni equivalencia bajo carga.',
  initialPhenomenon: 'Con los mismos resistores, el indicador responde con retorno cerrado y no responde abierto aunque N2 pueda quedar a 5,00 V respecto de REF.',
  researchQuestion: '¿Qué combinación de topología, continuidad y tensiones distingue camino completo de retorno abierto?',
  expectedHypotheses: 'Open impide I; tensión nodal no demuestra corriente; resistores pueden estar sanos; continuidad no garantiza carga.',
  availableInstruments: 'Esquema nodal, selector de retorno, solver de topología, medidor virtual V/R/continuidad y registro.',
  allowedInteractions: 'Predecir; aislar; consultar resistencia/continuidad; energizar bloqueado; medir tensiones; volver a aislar; intervenir y verificar.',
  simulatedConsequences: 'Closed: Req=250 ohm, I=20,00 mA, nodos 5/3/0/0 V, P1=0,040 W y P2=0,060 W; open: I=0, nodos 5/5/5/0 V.',
  productiveErrors: 'Inferir I por tensión; llamar continuidad a prueba energizada; culpar resistores; decir que la carga consume corriente; intervenir energizado.',
  evidenceHints: 'Comparar N1−REF, N2−REF y N2−REF pasivo; exigir que toda conclusión nombre estado, puntos, magnitud y unidad.',
  masteryCriteria: 'Calcula Req/I/nodos/potencias, reconoce ∞, explica tensión sobre la apertura y conserva la topología al bloquear intervención.',
  transfer: 'Resuelve la misma red rotulada como bisagras de la Puerta y admite un orden alternativo de evidencias.',
  diegeticMetaphor: 'Una ruta luminosa necesita ida y regreso completos para sostener una respuesta.',
  metaphorLimit: 'Carga no es luz ni agua, no se consume en resistores y un brillo no demuestra seguridad.',
  localFormalVocabulary: 'Ruta/regreso/piedra ↔ trayectoria/retorno/resistor; marca ↔ nodo o referencia.',
  initialLogEntry: 'El brillo apagado no identifica la pieza: voy a comprobar la trayectoria y luego comparar tensiones bajo carga.',
  revisedLogEntry: 'Con retorno cerrado calculé 20,00 mA y obtuve N1=3,00 V, N2=0,00 V; abierto, I=0 y N2=5,00 V respecto de REF.',
  accessibility: 'Topología, estado, nodos, tabla de valores y apertura/cierre tienen alternativas textuales y orden de foco estable.',
  allowedTelemetry: TELEMETRY,
  deterministicTest: 'Verificar camino R1→R2→retorno, Req 250/∞, nodos, caídas, potencias, resistencias parciales y topología equivalente de Puerta.',
  validationStatus: STATUS,
});

export const instrumentCard = defineEducationCard({
  identifierVersion: 'H1.3-instrumento-ohm-v1',
  technicalName: 'Selección de magnitud, puntos, polaridad, rango y estado del instrumento exclusivamente virtual.',
  competencyLevel: 'F0 — Instrumentación básica simulada; no equivale a práctica con multímetro.',
  sources: SOURCES,
  reviewerDate: 'Autoría DIR-EDU-001, 2026-08-02; auditor independiente pendiente.',
  prerequisites: 'Distinguir V_DC, R y continuidad; reconocer puntos, referencia, signo, energía y comparación inclusiva.',
  observableObjective: 'Configurar una consulta completa, interpretar signo/límite/fuera de rango/apertura y usarla como evidencia sin habilitar intervención.',
  technicalModel: 'V_DC devuelve A−B energizado/bloqueado; R y CONTINUITY consultan la red pasiva desenergizada/aislada.',
  variablesUnits: 'Rangos V ±0,50/±5,00/±20,00; R 0–200/0–2000 ohm; continuidad <=300 ohm; qV=0,01 V, qR=1 ohm.',
  assumptionsLimits: 'Solver ideal sin error aleatorio; cuantización al más cercano; rangos y umbral son reglas didácticas, no propiedades de un instrumento real.',
  safetyRisks: 'No imita bornes, categorías ni fusibles reales; bloquea modo pasivo energizado y no enseña procedimientos sobre equipos.',
  initialPhenomenon: 'La misma red produce lectura positiva, negativa, al límite, fuera de rango, abierta o inválida según configuración y estado.',
  researchQuestion: '¿Qué configuración transforma una consulta en evidencia interpretable y qué errores impiden concluir?',
  expectedHypotheses: 'Invertir puntos cambia signo; ampliar rango no cambia circuito; out-of-range no es cero; modos pasivos exigen aislamiento.',
  availableInstruments: 'Selectores textuales de modo, A, B, rango y estado; pantalla con código, valor y unidad; historial estructurado.',
  allowedInteractions: 'Configurar en cualquier orden sin medición activa; medir V energizado bloqueado; medir R/continuidad aislado; cerrar y desenergizar antes de intervenir.',
  simulatedConsequences: 'Límite inclusivo marca AT_RANGE_LIMIT; desborde no expone valor; continuidad da CLOSED_PATH u OPEN_PATH; configuración inválida no lee.',
  productiveErrors: 'Campo ausente, nodo desconocido, rango incompatible, signo como falla, out-of-range como cero, modo pasivo energizado.',
  evidenceHints: 'Mostrar A−B y el campo ausente; diferenciar código físico de configuración; explicar inclusión del límite sin revelar diagnóstico.',
  masteryCriteria: 'Obtiene ±3,00 V al invertir puntos, elige menor rango contenedor, reconoce 250 ohm y apertura, y vuelve al estado seguro.',
  transfer: 'Configura mediciones equivalentes con etiquetas de Puerta y otro orden válido.',
  diegeticMetaphor: 'Ohm orienta dos marcas y traduce su diferencia a un registro.',
  metaphorLimit: 'Ohm no siente electricidad ni sustituye instrumental; sólo consulta un solver virtual.',
  localFormalVocabulary: 'Marca/orientación/alcance ↔ punto/polaridad/rango; ruta cerrada ↔ continuidad didáctica.',
  initialLogEntry: 'Antes de pedir un número debo elegir magnitud, dos puntos, orientación, rango y estado.',
  revisedLogEntry: 'N1−REF en V_DC y ±5,00 V dio +3,00 V; REF−N1 dio −3,00 V: cambió la comparación, no la red.',
  accessibility: 'Selectores etiquetados, signo+unidad anunciados, errores no cromáticos, resumen previo y foco recuperable.',
  allowedTelemetry: TELEMETRY,
  deterministicTest: 'Cubrir polaridad, cuantización, límites, desbordes, apertura, configuración incompleta, nodos inválidos y estados incompatibles.',
  validationStatus: STATUS,
});

export const lumenDiagnosisCard = defineEducationCard({
  identifierVersion: 'H1.4-diagnostico-lumen-v1',
  technicalName: 'Diagnóstico por hipótesis y evidencia del retorno abierto del circuito virtual de Lumen.',
  competencyLevel: 'F0 con puente a F1 — diagnóstico inicial, sin práctica certificada.',
  sources: SOURCES,
  reviewerDate: 'Autoría DIR-EDU-001, 2026-08-02; auditor independiente pendiente.',
  prerequisites: 'Dominar invariantes H1.1, topología H1.2 y configuración H1.3.',
  observableObjective: 'Localizar el retorno abierto sin sustitución ciega mediante inspección, hipótesis, al menos una evidencia válida, intervención protegida, verificación y registro.',
  technicalModel: 'Máquina de estados pura con energía, medición activa, inspección, hipótesis, configuración, evidencias, intervención, verificación y documentación.',
  variablesUnits: 'Estados de workflow; evidencia continuity/voltage; valores de H1.2–H1.3 en V y ohm.',
  assumptionsLimits: 'Sólo falla open/closed del retorno ideal; no diagnostica cortos, degradación, tolerancias ni sistemas físicos.',
  safetyRisks: 'Evitar ritual de recambio, intervención energizada o prueba pasiva energizada; el modelo bloquea sin alterar estado previo.',
  initialPhenomenon: 'Lumen propone tres piezas habituales, pero los dos resistores conservan valor y el retorno está abierto.',
  researchQuestion: '¿Qué evidencia separa una pieza defectuosa de una interrupción en el regreso?',
  expectedHypotheses: 'R1/R2 sanos y retorno open; N2 alto respecto de REF sin I; continuidad N2–REF abierta.',
  availableInstruments: 'Inspección, hipótesis codificada, medidor H1.3, esquema H1.2, selector protegido y Bitácora.',
  allowedInteractions: 'Configurar antes o después de inspeccionar; inspeccionar→hipótesis; medir continuidad o tensión en estado compatible; aislar; intervenir; energizar; verificar; documentar.',
  simulatedConsequences: 'Intervención cierra el retorno sólo aislado y con evidencia; verificación energizada reproduce 20,00 mA calculados y nodos esperados.',
  productiveErrors: 'Hipótesis antes de inspección, medir sin configurar, intervenir sin evidencia, no cerrar medición, documentar sin verificar.',
  evidenceHints: 'Señalar la precondición ausente y conservar intentos; aceptar continuidad-primero o tensión-primero.',
  masteryCriteria: 'Completa uno de varios órdenes válidos, explica por qué el retorno era la causa y verifica predicción sin recambio ciego.',
  transfer: 'En la Puerta repite la estrategia con otros rótulos, no la secuencia memorizada.',
  diegeticMetaphor: 'Lumen deja de preguntar qué piedra suele funcionar y empieza a seguir marcas y regreso.',
  metaphorLimit: 'Las piedras son carcasas narrativas; el diagnóstico válido procede de topología y mediciones virtuales.',
  localFormalVocabulary: 'Ritual/rastro/piedra/regreso ↔ sustitución ciega/evidencia/resistor/retorno.',
  initialLogEntry: 'No voy a elegir una piedra por costumbre: registraré qué tramo sospecho y qué lectura podría refutarlo.',
  revisedLogEntry: 'R1 y R2 conservaron 100 y 150 ohm; N2−REF mostró apertura aislada y 5,00 V energizado: cerré el retorno, verifiqué y documenté.',
  accessibility: 'Workflow linealizable con teclado/táctil, historial textual de precondiciones, tabla de evidencia y errores recuperables.',
  allowedTelemetry: TELEMETRY,
  deterministicTest: 'Aceptar órdenes continuidad-primero y tensión-primero; rechazar hipótesis precoz, estados incompatibles, intervención y documentación inválidas.',
  validationStatus: STATUS,
});

export const puertaTransferCard = defineEducationCard({
  identifierVersion: 'H1.5-puerta-transferencia-v1',
  technicalName: 'Transferencia de circuito completo y diagnóstico protegido en la Puerta de Ohm.',
  competencyLevel: 'F0/F1 inicial — transferencia de estrategia en representación distinta.',
  sources: SOURCES,
  reviewerDate: 'Autoría DIR-EDU-001, 2026-08-02; auditor independiente pendiente.',
  prerequisites: 'Completar H1.4 y explicar evidencia sin depender de la metáfora de Lumen.',
  observableObjective: 'Reconocer la topología equivalente bajo nuevos rótulos y resolverla con un orden válido distinto o justificadamente elegido.',
  technicalModel: 'Misma red 5 V, 100+150 ohm y retorno open/closed; rótulos V_PLUS/N1/N2/REF cambian a marca_este/bisagra_alta/bisagra_baja/marca_oeste.',
  variablesUnits: 'Mismas variables V, A/mA, ohm y W; sólo cambia el mapeo espacial/semántico de nodos.',
  assumptionsLimits: 'No agrega fórmula, componente, tensión, falla ni herramienta; prueba transferencia del modelo ya validado.',
  safetyRisks: 'La presión narrativa no habilita intervención energizada; los bloqueos H1.1 se conservan íntegros.',
  initialPhenomenon: 'La puerta no abre aunque sus bisagras y trazas se disponen de forma diferente al banco de Lumen.',
  researchQuestion: '¿Qué relaciones permanecen cuando cambia la forma visible y qué evidencia mínima permite intervenir?',
  expectedHypotheses: 'Los nuevos rótulos forman el mismo camino serie; el regreso open produce los mismos valores nodales equivalentes.',
  availableInstruments: 'Mapa accesible de rótulos, medidor H1.3, workflow H1.4 y predicción previa.',
  allowedInteractions: 'Elegir continuidad-primero o tensión-primero; mapear nodos; medir; aislar; intervenir; energizar; verificar y registrar.',
  simulatedConsequences: 'El solver devuelve exactamente la solución de H1.2; sólo la representación y el orden observacional cambian.',
  productiveErrors: 'Buscar una fórmula nueva, seguir posiciones en vez de conectividad, intervenir por urgencia o exigir un único orden.',
  evidenceHints: 'Permitir superponer rótulos formales después de la hipótesis; comparar conectividad, no apariencia.',
  masteryCriteria: 'Construye el mapeo de cuatro nodos, predice valores, completa un orden seguro y explica equivalencia causal.',
  transfer: 'Es en sí la transferencia; prepara variantes futuras sólo de disposición, no de alcance curricular.',
  diegeticMetaphor: 'La Puerta responde a una ruta comprendida, no a una palabra secreta.',
  metaphorLimit: 'Abrir una puerta no representa energía gratis ni prueba reparación real; es feedback del solver.',
  localFormalVocabulary: 'Marca este/oeste y bisagra alta/baja ↔ V_PLUS/REF y N1/N2.',
  initialLogEntry: 'La forma cambió; voy a reconstruir qué marcas están conectadas antes de repetir una acción.',
  revisedLogEntry: 'Mapeé marca_este→V_PLUS, bisagras→N1/N2 y marca_oeste→REF; la misma apertura produjo la misma evidencia y verificación.',
  accessibility: 'Mapa textual de equivalencias, conectividad no dependiente de perspectiva/color y puntos alcanzables por teclado/táctil.',
  allowedTelemetry: TELEMETRY,
  deterministicTest: 'Comparar soluciones Lumen/Puerta nodo por nodo y aceptar al menos dos órdenes sin permitir intervención insegura.',
  validationStatus: STATUS,
});

export const bitacoraCard = defineEducationCard({
  identifierVersion: 'H1.6-bitacora-evidencia-v1',
  technicalName: 'Registro estructurado de vivencia, evidencia, traducción formal y siguiente pregunta.',
  competencyLevel: 'F0 transversal — documentación y comunicación técnica.',
  sources: SOURCES,
  reviewerDate: 'Autoría DIR-EDU-001, 2026-08-02; auditor independiente pendiente.',
  prerequisites: 'Haber vivido y verificado H1.2–H1.5; distinguir observación, hipótesis, evidencia e interpretación.',
  observableObjective: 'Dejar un registro reproducible que otra persona pueda seguir sin convertirlo en tutorial anticipado.',
  technicalModel: 'Entrada con cuatro bloques obligatorios: vivencia ilustrada, evidencia estructurada, traducción formal y siguiente pregunta; URL https opcional.',
  variablesUnits: 'Evidencia: hipótesis, A, B, magnitud, valor y unidad; traducción: nombre, variables, supuestos y límite metafórico.',
  assumptionsLimits: 'No evalúa estilo ni verdad de texto libre; valida completitud estructural y protocolo seguro de un enlace opcional.',
  safetyRisks: 'No almacenar identidad ni instrucciones físicas; no presentar la evaluación externa como obligatoria o bloqueo.',
  initialPhenomenon: 'La página empieza con el recuerdo del indicador y la duda, no con fórmula ni respuesta completada de antemano.',
  researchQuestion: '¿Qué debe quedar escrito para que otra persona reproduzca la conclusión y conozca sus límites?',
  expectedHypotheses: 'Una lectura sin puntos/estado no alcanza; la formalización necesita supuestos; la próxima pregunta mantiene transferencia.',
  availableInstruments: 'Croquis o frase, tabla de evidencia, campos formales, siguiente pregunta y enlace opcional en pestaña nueva.',
  allowedInteractions: 'Registrar después de vivir; revisar hipótesis; agregar evidencia estructurada; formalizar; escribir siguiente pregunta; omitir evaluación.',
  simulatedConsequences: 'Falta de cualquiera de los cuatro bloques produce INCOMPLETE_RECORD; URL no https produce INVALID_EVALUATION_URL; no bloquea juego.',
  productiveErrors: 'Tutorial anticipado, lectura sin referencia, metáfora como explicación, evaluación obligatoria, telemetría de texto libre.',
  evidenceHints: 'Pedir el campo faltante y mostrar ejemplos de estructura, nunca completar la interpretación por el jugador.',
  masteryCriteria: 'Una tercera persona identifica hipótesis, puntos, magnitud, valor/unidad, supuestos, límite y pregunta de transferencia.',
  transfer: 'El registro permite a Lumen repetir el método y enlaza opcionalmente una evaluación externa sin afectar viaje o final.',
  diegeticMetaphor: 'La página se reescribe cuando una vivencia se convierte en evidencia compartible.',
  metaphorLimit: 'La Bitácora no certifica dominio, no reemplaza una evaluación y no vuelve verdadera una conclusión incompleta.',
  localFormalVocabulary: 'Vivencia/evidencia/traducción/pregunta ↔ observación/medición/modelo/transferencia.',
  initialLogEntry: 'La luz se apagó y Lumen recordó una piedra; todavía falta separar recuerdo, hipótesis y evidencia.',
  revisedLogEntry: 'Calculé 20,00 mA para el retorno cerrado; registré puntos, magnitud, valores, supuestos y por qué 5,00 V en N2 abierto no implica corriente.',
  accessibility: 'Cuatro encabezados semánticos, tablas legibles, texto alternativo para croquis, foco estable y evaluación explícitamente opcional.',
  allowedTelemetry: TELEMETRY,
  deterministicTest: 'Validar los cuatro bloques, cada campo de evidencia, URL https opcional y proyección de telemetría sin texto ni identidad.',
  validationStatus: STATUS,
});

export const EDUCATION_CARDS = Object.freeze({
  safety: safetyCard,
  circuit: circuitCard,
  instrument: instrumentCard,
  lumenDiagnosis: lumenDiagnosisCard,
  puertaTransfer: puertaTransferCard,
  bitacora: bitacoraCard,
}) satisfies Readonly<Record<string, EducationCard>>;
